In [126]:
# importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [127]:
# import dataset
df = pd.read_csv('homework_sesi29.csv')
print(df)

                                                                            texts Sentiment
0  Saya tidak mau! Pokoknya hari ini kamu harus pulang!!!                          Negatif
1  Kenapa kamu masih mencari yang lain????                                         Negatif
2  Ada 3 buku yang belum aku baca, 2 diantaranya masih dibungkus                   Netral
3  Hebat! Kamu memang pantas jadi juara!!                                          Positif
4  Selamat berakhir pekan teman-teman semua :)))                                   Positif
5  Halo! Perkenalkan aku Budi. Umurku 20 tahun. Salam kenal!                       Positif
6  Masakan mama enak sekali!                                                       Positif
7  Sepertinya aku belum coba ini, kamu gimana? @kawanku                            Netral
8  Lelah banget pulang sekolah. Mau tidur aja rasanya #capek #lelah #letih         Netral
9  Tempat ini kotor sekali! Aku tidak mau kesini lagi! http://www.tempatkotor.com  Negatif

#Cleaning

In [128]:
import nltk
nltk.download ('stopwords')
nltk.download ('punkt')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [129]:
# df['texts']=df['texts'].convert_dtypes(str)
# df['texts'] = pd.Series(df['texts'], dtype="string")
# obj = lambda x:x[1:]
# df['texts']=df['texts'].apply(obj).astype('str')
# df['texts']=df['texts'].to_string()

In [130]:
print(type(df['texts']))

<class 'pandas.core.series.Series'>

In [131]:
#change to lower case
df['texts']=df['texts'].str.lower()
df

                                                                            texts Sentiment
0  saya tidak mau! pokoknya hari ini kamu harus pulang!!!                          Negatif
1  kenapa kamu masih mencari yang lain????                                         Negatif
2  ada 3 buku yang belum aku baca, 2 diantaranya masih dibungkus                   Netral
3  hebat! kamu memang pantas jadi juara!!                                          Positif
4  selamat berakhir pekan teman-teman semua :)))                                   Positif
5  halo! perkenalkan aku budi. umurku 20 tahun. salam kenal!                       Positif
6  masakan mama enak sekali!                                                       Positif
7  sepertinya aku belum coba ini, kamu gimana? @kawanku                            Netral
8  lelah banget pulang sekolah. mau tidur aja rasanya #capek #lelah #letih         Netral
9  tempat ini kotor sekali! aku tidak mau kesini lagi! http://www.tempatkotor.com  Negatif

In [132]:
#delete number in texts

import re # impor modul regular expression
#use regexr
hasil=[]
for x in df['texts']:
  x =re.sub(r"\d+", "", x)
  hasil.append(x)
# print(hasil)
df['texts']=hasil
pd.set_option("display.max_colwidth", -1)
df

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  # This is added back by InteractiveShellApp.init_path()

                                                                            texts Sentiment
0  saya tidak mau! pokoknya hari ini kamu harus pulang!!!                          Negatif
1  kenapa kamu masih mencari yang lain????                                         Negatif
2  ada  buku yang belum aku baca,  diantaranya masih dibungkus                     Netral
3  hebat! kamu memang pantas jadi juara!!                                          Positif
4  selamat berakhir pekan teman-teman semua :)))                                   Positif
5  halo! perkenalkan aku budi. umurku  tahun. salam kenal!                         Positif
6  masakan mama enak sekali!                                                       Positif
7  sepertinya aku belum coba ini, kamu gimana? @kawanku                            Netral
8  lelah banget pulang sekolah. mau tidur aja rasanya #capek #lelah #letih         Netral
9  tempat ini kotor sekali! aku tidak mau kesini lagi! http://www.tempatkotor.com  Negatif

In [133]:
#delete link and @
hasil=[]
for x in df['texts']:
  x =re.sub(r"(?:\@|http?\://|https?\://|www)\S+", "", x)
  hasil.append(x)
# print(hasil)
df['texts']=hasil
pd.set_option("display.max_colwidth", -1)
df

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.

                                                                     texts Sentiment
0  saya tidak mau! pokoknya hari ini kamu harus pulang!!!                   Negatif
1  kenapa kamu masih mencari yang lain????                                  Negatif
2  ada  buku yang belum aku baca,  diantaranya masih dibungkus              Netral
3  hebat! kamu memang pantas jadi juara!!                                   Positif
4  selamat berakhir pekan teman-teman semua :)))                            Positif
5  halo! perkenalkan aku budi. umurku  tahun. salam kenal!                  Positif
6  masakan mama enak sekali!                                                Positif
7  sepertinya aku belum coba ini, kamu gimana?                              Netral
8  lelah banget pulang sekolah. mau tidur aja rasanya #capek #lelah #letih  Netral
9  tempat ini kotor sekali! aku tidak mau kesini lagi!                      Negatif

In [134]:
#delete tanda baca
import string

hasil=[]
for x in df['texts']:
  x =x.translate(str.maketrans("","",string.punctuation))
  hasil.append(x)
df['texts']=hasil
pd.set_option("display.max_colwidth", -1)
df
#I still keep # (hastags)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  if __name__ == '__main__':

                                                                 texts Sentiment
0  saya tidak mau pokoknya hari ini kamu harus pulang                   Negatif
1  kenapa kamu masih mencari yang lain                                  Negatif
2  ada  buku yang belum aku baca  diantaranya masih dibungkus           Netral
3  hebat kamu memang pantas jadi juara                                  Positif
4  selamat berakhir pekan temanteman semua                              Positif
5  halo perkenalkan aku budi umurku  tahun salam kenal                  Positif
6  masakan mama enak sekali                                             Positif
7  sepertinya aku belum coba ini kamu gimana                            Netral
8  lelah banget pulang sekolah mau tidur aja rasanya capek lelah letih  Netral
9  tempat ini kotor sekali aku tidak mau kesini lagi                    Negatif

#Tokenizing

In [137]:
#create token
def cleaning_tokenizing(txt):
  txt = txt.lower() # menjadi huruf kecil semua
  txt = txt.translate(str.maketrans("","",string.punctuation)) #hapus symbol
  txt = nltk.tokenize.word_tokenize(txt) # tokenize
  return txt
df["texts"].apply(cleaning_tokenizing)

0    [saya, tidak, mau, pokoknya, hari, ini, kamu, harus, pulang]
1    [kenapa, kamu, masih, mencari, yang, lain]
2    [ada, buku, yang, belum, aku, baca, diantaranya, masih, dibungkus]
3    [hebat, kamu, memang, pantas, jadi, juara]
4    [selamat, berakhir, pekan, temanteman, semua]
5    [halo, perkenalkan, aku, budi, umurku, tahun, salam, kenal]
6    [masakan, mama, enak, sekali]
7    [sepertinya, aku, belum, coba, ini, kamu, gimana]
8    [lelah, banget, pulang, sekolah, mau, tidur, aja, rasanya, capek, lelah, letih]
9    [tempat, ini, kotor, sekali, aku, tidak, mau, kesini, lagi]
Name: texts, dtype: object

#Vectorization (Bag of Words and TF-IDF)

In [138]:
#do CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
text_counts= cv.fit_transform(df["texts"])
pd.DataFrame(text_counts.toarray(), columns = cv.get_feature_names())

   ada  aja  aku  baca  banget  ...  tempat  tidak  tidur  umurku  yang
0  0    0    0    0     0       ...  0       1      0      0       0
1  0    0    0    0     0       ...  0       0      0      0       1
2  1    0    1    1     0       ...  0       0      0      0       1
3  0    0    0    0     0       ...  0       0      0      0       0
4  0    0    0    0     0       ...  0       0      0      0       0
5  0    0    1    0     0       ...  0       0      0      1       0
6  0    0    0    0     0       ...  0       0      0      0       0
7  0    0    1    0     0       ...  0       0      0      0       0
8  0    1    0    0     1       ...  0       0      1      0       0
9  0    0    1    0     0       ...  1       1      0      0       0

[10 rows x 57 columns]

In [139]:
from sklearn.feature_extraction.text import TfidfVectorizer
cv = TfidfVectorizer()
text_counts= cv.fit_transform(df["texts"])
pd.DataFrame(text_counts.toarray(), columns = cv.get_feature_names())

        ada       aja       aku  ...     tidur    umurku      yang
0  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
1  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.384718
2  0.362614  0.000000  0.239771  ...  0.000000  0.000000  0.308255
3  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
4  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
5  0.000000  0.000000  0.242463  ...  0.000000  0.366686  0.000000
6  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
7  0.000000  0.000000  0.291366  ...  0.000000  0.000000  0.000000
8  0.000000  0.285414  0.000000  ...  0.285414  0.000000  0.000000
9  0.000000  0.000000  0.250121  ...  0.000000  0.000000  0.000000

[10 rows x 57 columns]